name: bn-mobile-server

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
    command: ["/bin/sh", "-c", "/app/bin/migrate -action up && /app/bin/server"]
    ports:
      - "${SERVER_PORT:-8080}:8080"
