CREATE TABLE IF NOT EXISTS hijaiyah_letters (
    id              VARCHAR(50)  PRIMARY KEY,
    arabic          VARCHAR(10)  NOT NULL,
    name            VARCHAR(50)  NOT NULL,
    transliteration VARCHAR(10)  NOT NULL,
    pronunciation   VARCHAR(50)  NOT NULL,
    audio_url       VARCHAR(500),
    sort_order      INT          NOT NULL DEFAULT 0,
    description     TEXT,
    writing_steps   JSONB        NOT NULL DEFAULT '[]',
    stroke_points   JSONB        NOT NULL DEFAULT '[]',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quiz_categories (
    id          VARCHAR(50)  PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT         NOT NULL,
    icon        VARCHAR(50)  NOT NULL,
    color       VARCHAR(50)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quiz_questions (
    id             VARCHAR(50)  PRIMARY KEY,
    question       TEXT         NOT NULL,
    options        JSONB        NOT NULL DEFAULT '[]',
    correct_answer INT          NOT NULL,
    explanation    TEXT         NOT NULL,
    material       TEXT         NOT NULL,
    category_id    VARCHAR(50)  NOT NULL REFERENCES quiz_categories(id) ON DELETE CASCADE,
    difficulty     VARCHAR(10)  NOT NULL CHECK (difficulty IN ('easy','medium','hard')),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS quran_surahs (
    id               INT          PRIMARY KEY,
    name             VARCHAR(100) NOT NULL,
    arabic_name      VARCHAR(200) NOT NULL,
    english_name     VARCHAR(200) NOT NULL,
    number_of_ayahs  INT          NOT NULL,
    revelation_type  VARCHAR(10)  NOT NULL CHECK (revelation_type IN ('Meccan','Medinan')),
    audio_url        VARCHAR(500),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_hijaiyah_sort_order     ON hijaiyah_letters (sort_order);
CREATE INDEX IF NOT EXISTS idx_quiz_questions_category ON quiz_questions (category_id);
CREATE INDEX IF NOT EXISTS idx_quiz_questions_diff     ON quiz_questions (difficulty);

-- ===================== SEED DATA =====================

DELETE FROM quiz_questions;
DELETE FROM quiz_categories;
DELETE FROM hijaiyah_letters;
DELETE FROM quran_surahs;

-- ==================== HIJAIYAH LETTERS ====================

INSERT INTO hijaiyah_letters (id, arabic, name, transliteration, pronunciation, audio_url, sort_order, description, writing_steps, stroke_points) VALUES
('alif', 'ا', 'Alif', 'A', 'Alif', '/audio/hijaiyah/alif.mp3', 1, 'Huruf pertama dalam alfabet Arab', '["Tarik garis lurus dari atas ke bawah"]', '[{"x":50,"y":20},{"x":50,"y":35},{"x":50,"y":50},{"x":50,"y":65},{"x":50,"y":80}]'),
('ba', 'ب', 'Ba', 'B', 'Ba', '/audio/hijaiyah/ba.mp3', 2, 'Huruf kedua dalam alfabet Arab', '["Buat garis melengkung","Tambahkan satu titik di bawah"]', '[{"x":80,"y":40},{"x":85,"y":60},{"x":70,"y":70},{"x":50,"y":70},{"x":30,"y":70},{"x":15,"y":60},{"x":20,"y":40}]'),
('ta', 'ت', 'Ta', 'T', 'Ta', '/audio/hijaiyah/ta.mp3', 3, 'Huruf ketiga dalam alfabet Arab', '["Buat garis melengkung seperti Ba","Tambahkan dua titik di atas"]', '[{"x":80,"y":40},{"x":85,"y":60},{"x":70,"y":70},{"x":50,"y":70},{"x":30,"y":70},{"x":15,"y":60},{"x":20,"y":40},{"x":40,"y":25},{"x":60,"y":25}]'),
('tsa', 'ث', 'Tsa', 'Ts', 'Tsa', '/audio/hijaiyah/tsa.mp3', 4, 'Huruf keempat dalam alfabet Arab', '["Buat garis melengkung seperti Ba","Tambahkan tiga titik di atas"]', '[{"x":80,"y":40},{"x":85,"y":60},{"x":70,"y":70},{"x":50,"y":70},{"x":30,"y":70},{"x":15,"y":60},{"x":20,"y":40},{"x":40,"y":25},{"x":60,"y":25},{"x":50,"y":15}]'),
('jim', 'ج', 'Jim', 'J', 'Jim', '/audio/hijaiyah/jim.mp3', 5, 'Huruf kelima dalam alfabet Arab', '["Buat setengah lingkaran","Tambahkan garis vertikal","Tambahkan satu titik di bawah"]', '[{"x":75,"y":30},{"x":50,"y":30},{"x":25,"y":30},{"x":15,"y":50},{"x":25,"y":75},{"x":50,"y":85},{"x":75,"y":75},{"x":50,"y":55}]'),
('ha', 'ح', 'Ha', 'H', 'Ha', '/audio/hijaiyah/ha.mp3', 6, 'Huruf keenam dalam alfabet Arab', '["Buat setengah lingkaran seperti Jim tanpa titik"]', '[{"x":75,"y":30},{"x":50,"y":30},{"x":25,"y":30},{"x":15,"y":50},{"x":25,"y":75},{"x":50,"y":85},{"x":75,"y":75}]'),
('kha', 'خ', 'Kha', 'Kh', 'Kha', '/audio/hijaiyah/kha.mp3', 7, 'Huruf ketujuh dalam alfabet Arab', '["Buat setengah lingkaran seperti Ha","Tambahkan satu titik di atas"]', '[{"x":75,"y":30},{"x":50,"y":30},{"x":25,"y":30},{"x":15,"y":50},{"x":25,"y":75},{"x":50,"y":85},{"x":75,"y":75},{"x":50,"y":15}]'),
('dal', 'د', 'Dal', 'D', 'Dal', '/audio/hijaiyah/dal.mp3', 8, 'Huruf kedelapan dalam alfabet Arab', '["Buat garis melengkung pendek dengan ekor di atas"]', '[{"x":65,"y":35},{"x":45,"y":45},{"x":40,"y":65},{"x":55,"y":80},{"x":75,"y":80}]'),
('dzal', 'ذ', 'Dzal', 'Dz', 'Dzal', '/audio/hijaiyah/dzal.mp3', 9, 'Huruf kesembilan dalam alfabet Arab', '["Buat seperti Dal","Tambahkan satu titik di atas"]', '[{"x":65,"y":35},{"x":45,"y":45},{"x":40,"y":65},{"x":55,"y":80},{"x":75,"y":80},{"x":55,"y":20}]'),
('ra', 'ر', 'Ra', 'R', 'Ra', '/audio/hijaiyah/ra.mp3', 10, 'Huruf kesepuluh dalam alfabet Arab', '["Buat garis pendek dengan lengkungan kecil"]', '[{"x":50,"y":40},{"x":55,"y":55},{"x":50,"y":70},{"x":35,"y":80},{"x":20,"y":80}]'),
('zay', 'ز', 'Zay', 'Z', 'Zay', '/audio/hijaiyah/zay.mp3', 11, 'Huruf kesebelas dalam alfabet Arab', '["Buat seperti Ra","Tambahkan satu titik di atas"]', '[{"x":50,"y":40},{"x":55,"y":55},{"x":50,"y":70},{"x":35,"y":80},{"x":20,"y":80},{"x":60,"y":25}]'),
('sin', 'س', 'Sin', 'S', 'Sin', '/audio/hijaiyah/sin.mp3', 12, 'Huruf kedua belas dalam alfabet Arab', '["Buat tiga gelombang berturut-turut"]', '[{"x":80,"y":45},{"x":75,"y":55},{"x":70,"y":45},{"x":65,"y":55},{"x":60,"y":45},{"x":55,"y":65},{"x":45,"y":80},{"x":25,"y":80},{"x":15,"y":65}]'),
('syin', 'ش', 'Syin', 'Sy', 'Syin', '/audio/hijaiyah/syin.mp3', 13, 'Huruf ketiga belas dalam alfabet Arab', '["Buat seperti Sin","Tambahkan tiga titik di atas"]', '[{"x":80,"y":45},{"x":75,"y":55},{"x":70,"y":45},{"x":65,"y":55},{"x":60,"y":45},{"x":55,"y":65},{"x":45,"y":80},{"x":25,"y":80},{"x":15,"y":65},{"x":60,"y":25},{"x":75,"y":25},{"x":67,"y":15}]'),
('shad', 'ص', 'Shad', 'Sh', 'Shad', '/audio/hijaiyah/shad.mp3', 14, 'Huruf keempat belas dalam alfabet Arab', '["Buat oval dengan ekor panjang"]', '[{"x":55,"y":60},{"x":80,"y":60},{"x":90,"y":50},{"x":80,"y":45},{"x":55,"y":50},{"x":55,"y":65},{"x":45,"y":80},{"x":25,"y":80},{"x":15,"y":65}]'),
('dhad', 'ض', 'Dhad', 'Dh', 'Dhad', '/audio/hijaiyah/dhad.mp3', 15, 'Huruf kelima belas dalam alfabet Arab', '["Buat seperti Shad","Tambahkan satu titik di atas"]', '[{"x":55,"y":60},{"x":80,"y":60},{"x":90,"y":50},{"x":80,"y":45},{"x":55,"y":50},{"x":55,"y":65},{"x":45,"y":80},{"x":25,"y":80},{"x":15,"y":65},{"x":70,"y":25}]'),
('tha', 'ط', 'Tha', 'Th', 'Tha', '/audio/hijaiyah/tha.mp3', 16, 'Huruf keenam belas dalam alfabet Arab', '["Buat oval dengan garis vertikal di tengah"]', '[{"x":30,"y":65},{"x":55,"y":65},{"x":75,"y":65},{"x":85,"y":55},{"x":75,"y":45},{"x":30,"y":45},{"x":45,"y":15},{"x":45,"y":40},{"x":45,"y":65}]'),
('zha', 'ظ', 'Zha', 'Zh', 'Zha', '/audio/hijaiyah/zha.mp3', 17, 'Huruf ketujuh belas dalam alfabet Arab', '["Buat seperti Tha","Tambahkan satu titik di atas"]', '[{"x":30,"y":65},{"x":55,"y":65},{"x":75,"y":65},{"x":85,"y":55},{"x":75,"y":45},{"x":30,"y":45},{"x":45,"y":15},{"x":45,"y":40},{"x":45,"y":65},{"x":60,"y":30}]'),
('ain', 'ع', 'Ain', '''', 'Ain', '/audio/hijaiyah/ain.mp3', 18, 'Huruf kedelapan belas dalam alfabet Arab', '["Buat lingkaran dengan bukaan di atas"]', '[{"x":65,"y":35},{"x":55,"y":25},{"x":45,"y":35},{"x":55,"y":45},{"x":45,"y":60},{"x":25,"y":80},{"x":50,"y":90},{"x":75,"y":80}]'),
('ghain', 'غ', 'Ghain', 'Gh', 'Ghain', '/audio/hijaiyah/ghain.mp3', 19, 'Huruf kesembilan belas dalam alfabet Arab', '["Buat seperti Ain","Tambahkan satu titik di atas"]', '[{"x":65,"y":35},{"x":55,"y":25},{"x":45,"y":35},{"x":55,"y":45},{"x":45,"y":60},{"x":25,"y":80},{"x":50,"y":90},{"x":75,"y":80},{"x":60,"y":15}]'),
('fa', 'ف', 'Fa', 'F', 'Fa', '/audio/hijaiyah/fa.mp3', 20, 'Huruf kedua puluh dalam alfabet Arab', '["Buat lingkaran dengan garis di atas","Tambahkan satu titik di atas"]', '[{"x":75,"y":45},{"x":85,"y":55},{"x":75,"y":65},{"x":65,"y":55},{"x":75,"y":45},{"x":65,"y":70},{"x":45,"y":75},{"x":15,"y":75},{"x":10,"y":60},{"x":75,"y":25}]'),
('qaf', 'ق', 'Qaf', 'Q', 'Qaf', '/audio/hijaiyah/qaf.mp3', 21, 'Huruf kedua puluh satu dalam alfabet Arab', '["Buat seperti Fa","Tambahkan dua titik di atas"]', '[{"x":75,"y":45},{"x":85,"y":55},{"x":75,"y":65},{"x":65,"y":55},{"x":75,"y":45},{"x":65,"y":75},{"x":45,"y":85},{"x":25,"y":85},{"x":15,"y":70},{"x":65,"y":25},{"x":85,"y":25}]'),
('kaf', 'ك', 'Kaf', 'K', 'Kaf', '/audio/hijaiyah/kaf.mp3', 22, 'Huruf kedua puluh dua dalam alfabet Arab', '["Buat bentuk seperti mangkuk dengan garis di atas"]', '[{"x":30,"y":20},{"x":30,"y":45},{"x":30,"y":70},{"x":50,"y":75},{"x":75,"y":70},{"x":80,"y":55},{"x":50,"y":45},{"x":65,"y":45}]'),
('lam', 'ل', 'Lam', 'L', 'Lam', '/audio/hijaiyah/lam.mp3', 23, 'Huruf kedua puluh tiga dalam alfabet Arab', '["Buat garis vertikal dengan lengkungan di bawah"]', '[{"x":60,"y":20},{"x":60,"y":45},{"x":60,"y":70},{"x":45,"y":85},{"x":25,"y":80},{"x":15,"y":65}]'),
('mim', 'م', 'Mim', 'M', 'Mim', '/audio/hijaiyah/mim.mp3', 24, 'Huruf kedua puluh empat dalam alfabet Arab', '["Buat lingkaran kecil dengan ekor"]', '[{"x":60,"y":40},{"x":75,"y":50},{"x":60,"y":60},{"x":45,"y":50},{"x":60,"y":40},{"x":40,"y":40},{"x":20,"y":40},{"x":20,"y":65},{"x":20,"y":85}]'),
('nun', 'ن', 'Nun', 'N', 'Nun', '/audio/hijaiyah/nun.mp3', 25, 'Huruf kedua puluh lima dalam alfabet Arab', '["Buat setengah lingkaran","Tambahkan satu titik di atas"]', '[{"x":80,"y":45},{"x":75,"y":70},{"x":50,"y":80},{"x":25,"y":70},{"x":20,"y":45},{"x":50,"y":25}]'),
('waw', 'و', 'Waw', 'W', 'Waw', '/audio/hijaiyah/waw.mp3', 26, 'Huruf kedua puluh enam dalam alfabet Arab', '["Buat lingkaran kecil dengan garis vertikal"]', '[{"x":65,"y":45},{"x":75,"y":55},{"x":65,"y":65},{"x":55,"y":55},{"x":65,"y":45},{"x":45,"y":70},{"x":30,"y":85}]'),
('ha2', 'ه', 'Ha', 'H', 'Ha', '/audio/hijaiyah/ha2.mp3', 27, 'Huruf kedua puluh tujuh dalam alfabet Arab', '["Buat oval dengan bukaan kecil"]', '[{"x":50,"y":30},{"x":75,"y":50},{"x":50,"y":80},{"x":25,"y":50},{"x":50,"y":30},{"x":50,"y":55}]'),
('ya', 'ي', 'Ya', 'Y', 'Ya', '/audio/hijaiyah/ya.mp3', 28, 'Huruf kedua puluh delapan dalam alfabet Arab', '["Buat garis melengkung","Tambahkan dua titik di bawah"]', '[{"x":80,"y":40},{"x":70,"y":30},{"x":55,"y":40},{"x":45,"y":55},{"x":50,"y":75},{"x":30,"y":75},{"x":15,"y":60},{"x":35,"y":90},{"x":55,"y":90}]');

-- ==================== QUIZ CATEGORIES ====================

INSERT INTO quiz_categories (id, name, description, icon, color) VALUES
('hijaiyah', 'Hijaiyah',          'Pengenalan huruf-huruf Arab',       'Languages', 'chart-1'),
('tajwid',   'Tajwid',            'Kaidah membaca Al-Qur''an',          'BookOpen',  'chart-2'),
('worship',  'Ibadah',            'Tata cara ibadah dalam Islam',      'Mosque',    'chart-3'),
('general',  'Pengetahuan Umum',  'Sejarah dan pengetahuan Islam',     'Globe',     'chart-4');

-- ==================== QUIZ QUESTIONS ====================

INSERT INTO quiz_questions (id, question, options, correct_answer, explanation, material, category_id, difficulty) VALUES
-- Hijaiyah
('h1',  'Huruf apakah ini: ب',                                                                       '["Alif","Ba","Ta","Tsa"]',                                                                                                    1, 'Huruf ب dibaca ''Ba'' dan merupakan huruf kedua dalam alfabet Arab.',                                                                                                                                        'Huruf Ba (ب) adalah huruf kedua dalam alfabet Arab. Huruf ini memiliki satu titik di bawah. Dalam pengucapannya, kedua bibir dirapatkan.',                                                                              'hijaiyah', 'easy'),
('h2',  'Berapa jumlah huruf Hijaiyah?',                                                             '["26","27","28","29"]',                                                                                                       2, 'Huruf Hijaiyah berjumlah 28 huruf, dari Alif hingga Ya.',                                                                                                                                                  'Huruf Hijaiyah adalah sistem alfabet yang digunakan dalam bahasa Arab dan Al-Qur''an. Secara umum, jumlah huruf dasar Hijaiyah adalah 28 huruf.',                                                                       'hijaiyah', 'easy'),
('h3',  'Huruf mana yang memiliki 3 titik di atas?',                                                 '["ت","ث","ج","خ"]',                                                                                                           1, 'Huruf ث (Tsa) memiliki 3 titik di atas, sedangkan ت (Ta) memiliki 2 titik.',                                                                                                                               'Beberapa huruf hijaiyah memiliki bentuk yang mirip namun dibedakan oleh titik. Huruf Ta (ت) punya 2 titik di atas, sedangkan Tsa (ث) punya 3 titik di atas.',                                                         'hijaiyah', 'medium'),
('h4',  'Huruf apakah ini: ج',                                                                       '["Ha","Kho","Jim","Dal"]',                                                                                                    2, 'Huruf ج dibaca ''Jim''.',                                                                                                                                                                                   'Huruf Jim (ج) memiliki satu titik di tengah perutnya. Pengucapannya keluar dari tengah lidah yang bertemu dengan langit-langit mulut.',                                                                                 'hijaiyah', 'easy'),
('h5',  'Manakah huruf ''Kho''?',                                                                    '["ح","خ","ج","ع"]',                                                                                                           1, 'Huruf خ adalah ''Kho''.',                                                                                                                                                                                   'Huruf Kho (خ) memiliki titik di atas kepalanya. Suaranya terdengar seperti suara ''ngorok'' halus yang keluar dari tenggorokan bagian atas.',                                                                           'hijaiyah', 'easy'),
('h6',  'Huruf ''Dal'' adalah...',                                                                   '["د","ذ","ر","ز"]',                                                                                                           0, 'Huruf د adalah ''Dal''.',                                                                                                                                                                                   'Huruf Dal (د) tidak memiliki titik. Pengucapannya dengan menyentuhkan ujung lidah ke pangkal gigi seri bagian atas.',                                                                                                  'hijaiyah', 'easy'),
('h7',  'Huruf ''Ra'' memiliki bentuk yang mirip dengan...',                                         '["Dal","Zain","Sin","Lam"]',                                                                                                  1, 'Ra (ر) mirip dengan Zain (ز).',                                                                                                                                                                            'Huruf Ra (ر) dan Zain (ز) memiliki bentuk yang sama, namun Zain memiliki satu titik di atasnya.',                                                                                                                       'hijaiyah', 'easy'),
('h8',  'Huruf Sin (س) memiliki berapa lekukan kecil di atasnya?',                                  '["1","2","3","4"]',                                                                                                           1, 'Sin memiliki 2 lekukan kecil di awal.',                                                                                                                                                                    'Huruf Sin (س) memiliki dua lekukan kecil dan satu lekukan besar di bawahnya. Sin tidak memiliki titik.',                                                                                                               'hijaiyah', 'medium'),
('h9',  'Manakah huruf Shad?',                                                                       '["س","ش","ص","ض"]',                                                                                                           2, 'Huruf ص adalah Shad.',                                                                                                                                                                                     'Huruf Shad (ص) diucapkan dengan suara desis yang kuat dan posisi lidah yang naik ke langit-langit (tebal).',                                                                                                           'hijaiyah', 'medium'),
('h10', 'Huruf yang diucapkan dengan ujung lidah menyentuh ujung gigi seri atas dan terdengar lembut adalah...', '["ت","ث","س","ص"]',                                                                                    1, 'Huruf ث (Tsa) diucapkan dengan ujung lidah.',                                                                                                                                                              'Huruf Tsa (ث) diucapkan dengan mengeluarkan sedikit ujung lidah di antara gigi seri atas dan bawah.',                                                                                                                   'hijaiyah', 'hard'),
-- Tajwid
('t1',  'Apa yang dimaksud dengan Tajwid?',                                                          '["Membaca Al-Qur''an dengan cepat","Membaca Al-Qur''an dengan benar sesuai kaidah","Menghafal Al-Qur''an","Menulis Al-Qur''an"]', 1, 'Tajwid adalah ilmu yang mempelajari cara membaca Al-Qur''an dengan benar sesuai kaidah yang telah ditetapkan.',                                                                                              'Secara bahasa, Tajwid berarti memperindah atau melakukan dengan baik. Dalam ilmu Al-Qur''an, Tajwid adalah ilmu untuk membaca Al-Qur''an dengan benar sesuai makhraj dan sifat hurufnya.',                              'tajwid',   'easy'),
('t2',  'Berapa panjang bacaan Mad Thobi''i?',                                                       '["1 harakat","2 harakat","4 harakat","6 harakat"]',                                                                            1, 'Mad Thobi''i dibaca sepanjang 2 harakat atau 2 ketukan.',                                                                                                                                                  'Mad Thobi''i atau Mad Ashli terjadi apabila ada Alif setelah fathah, Wawu sukun setelah dhommah, atau Ya sukun setelah kasroh. Panjangnya adalah 2 harakat.',                                                           'tajwid',   'medium'),
('t3',  'Hukum Nun Sukun bertemu dengan huruf ''Ba'' disebut...',                                    '["Izhari","Idgham","Iqlab","Ikhfa"]',                                                                                          2, 'Iqlab adalah mengganti suara Nun menjadi Mim saat bertemu Ba.',                                                                                                                                             'Iqlab secara bahasa berarti mengganti. Dalam tajwid, Iqlab terjadi jika Nun sukun atau Tanwin bertemu huruf Ba (ب), suaranya diganti menjadi Mim disertai dengung.',                                                    'tajwid',   'medium'),
('t4',  'Huruf-huruf Qolqolah terkumpul dalam kalimat...',                                           '["يَرْمَلُوْن","قُطْبُ جَدٍ","أَبْغِ حَجَّكَ","ءي"]',                                                                         1, 'Huruf Qolqolah adalah Qaf, Tha, Ba, Jim, Dal.',                                                                                                                                                           'Qolqolah berarti pantulan. Hurufnya ada 5: Qaf, Tha, Ba, Jim, Dal (ق، ط، ب، ج، د), yang sering disingkat ''Qutbu Jadin''.',                                                                                              'tajwid',   'medium'),
('t5',  'Apa arti dari ''Izhari''?',                                                                 '["Samar","Jelas","Memasukkan","Memantul"]',                                                                                    1, 'Izhar berarti dibaca dengan jelas tanpa dengung.',                                                                                                                                                         'Izhar secara bahasa berarti jelas. Dalam tajwid, Izhar Halqi terjadi jika Nun sukun atau Tanwin bertemu salah satu huruf tenggorokan (ء، هـ، ع، ح، غ، خ).',                                                              'tajwid',   'easy'),
('t6',  'Berapakah jumlah huruf Ikhfa Haqiqi?',                                                     '["5","10","15","20"]',                                                                                                        2, 'Ada 15 huruf Ikhfa Haqiqi.',                                                                                                                                                                               'Ikhfa berarti menyamarkan. Huruf Ikhfa Haqiqi berjumlah 15 huruf, yaitu selain huruf Izhar, Iqlab, dan Idgham.',                                                                                                       'tajwid',   'hard'),
('t7',  'Ghunnah artinya...',                                                                        '["Jelas","Dengung","Panjang","Pendek"]',                                                                                       1, 'Ghunnah adalah suara mendengung.',                                                                                                                                                                         'Ghunnah adalah suara yang keluar dari pangkal hidung. Hukum ini wajib dibaca pada Nun dan Mim yang bertasydid (نّ dan مّ).',                                                                                             'tajwid',   'easy'),
('t8',  'Hukum Alif Lam yang dibaca jelas disebut...',                                               '["Alif Lam Syamsiyah","Alif Lam Qomariyah","Alif Lam Ma''rifah","Alif Lam Nakirah"]',                                          1, 'Alif Lam Qomariyah dibaca jelas.',                                                                                                                                                                         'Alif Lam Qomariyah adalah hukum membaca Alif Lam secara jelas (Idzhar) ketika bertemu dengan 14 huruf tertentu.',                                                                                                       'tajwid',   'medium'),
('t9',  'Mad yang terjadi di akhir ayat karena waqof disebut...',                                    '["Mad Thobi''i","Mad Wajib Muttasil","Mad Arid Lissukun","Mad Jaiz Munfasil"]',                                                2, 'Mad Arid Lissukun terjadi karena waqof.',                                                                                                                                                                  'Mad Arid Lissukun terjadi jika ada Mad Thobi''i bertemu huruf hidup di akhir ayat atau tempat waqof. Panjangnya bisa 2, 4, atau 6 harakat.',                                                                            'tajwid',   'hard'),
('t10', 'Idgham Bighunnah artinya memasukkan suara dengan...',                                       '["Jelas","Dengung","Tanpa Dengung","Cepat"]',                                                                                  1, 'Idgham Bighunnah disertai dengan dengung.',                                                                                                                                                                'Idgham Bighunnah terjadi jika Nun sukun atau Tanwin bertemu huruf Ya, Nun, Mim, Wawu (ي، ن، م، و). Dibaca dengan memasukkan suara dan mendengung.',                                                                      'tajwid',   'medium'),
-- Worship
('w1',  'Berapa rakaat shalat Maghrib?',                                                             '["2 rakaat","3 rakaat","4 rakaat","5 rakaat"]',                                                                                1, 'Shalat Maghrib adalah 3 rakaat, terdiri dari 2 rakaat sirr dan 1 rakaat jahr.',                                                                                                                             'Shalat fardhu lima waktu memiliki jumlah rakaat yang berbeda: Subuh (2), Dhuhur (4), Ashar (4), Maghrib (3), dan Isya (4).',                                                                                             'worship',  'easy'),
('w2',  'Kapan waktu shalat Dhuha?',                                                                 '["Setelah terbit matahari hingga sebelum Dhuhur","Setelah Maghrib hingga Isya","Setelah Isya hingga Subuh","Setelah Subuh hingga terbit matahari"]', 0, 'Shalat Dhuha dilakukan setelah matahari terbit (naik setinggi tombak) hingga sebelum masuk waktu Dhuhur.', 'Shalat Dhuha adalah shalat sunnah yang dilakukan di pagi hari. Waktunya dimulai saat matahari mulai meninggi (sekitar 15 menit setelah terbit) hingga mendekati waktu Dhuhur.',                                          'worship',  'medium'),
('w3',  'Rukun Islam yang pertama adalah...',                                                        '["Shalat","Zakat","Syahadat","Puasa"]',                                                                                        2, 'Syahadat adalah rukun Islam yang pertama.',                                                                                                                                                                'Islam dibangun di atas lima rukun: Syahadat, Shalat, Zakat, Puasa, dan Haji bagi yang mampu.',                                                                                                                         'worship',  'easy'),
('w4',  'Membasuh muka dalam wudhu hukumnya...',                                                     '["Sunnah","Wajib/Rukun","Makruh","Mubah"]',                                                                                    1, 'Membasuh muka adalah salah satu rukun wudhu.',                                                                                                                                                             'Rukun wudhu ada enam: Niat, membasuh wajah, membasuh kedua tangan hingga siku, mengusap sebagian kepala, membasuh kedua kaki hingga mata kaki, dan tertib.',                                                            'worship',  'easy'),
('w5',  'Apa rukun iman yang ketiga?',                                                               '["Iman kepada Allah","Iman kepada Malaikat","Iman kepada Kitab-kitab","Iman kepada Rasul"]',                                    2, 'Beriman kepada Kitab-kitab Allah adalah rukun iman ketiga.',                                                                                                                                               'Rukun Iman ada enam: Beriman kepada Allah, Malaikat, Kitab-kitab-Nya, para Rasul-Nya, Hari Akhir, serta Qada dan Qadar.',                                                                                               'worship',  'medium'),
('w6',  'Puasa Ramadan hukumnya...',                                                                 '["Sunnah","Mubah","Wajib","Haram"]',                                                                                           2, 'Puasa Ramadan wajib bagi umat Muslim.',                                                                                                                                                                    'Puasa Ramadan adalah salah satu kewajiban bagi setiap Muslim yang sudah baligh, berakal, dan mampu melakukannya.',                                                                                                       'worship',  'easy'),
('w7',  'Arah kiblat umat Islam saat shalat adalah...',                                              '["Baitul Maqdis","Masjid Nabawi","Ka''bah","Masjid Quba"]',                                                                     2, 'Ka''bah adalah kiblat umat Islam.',                                                                                                                                                                         'Setiap Muslim wajib menghadap ke Ka''bah di Makkah (Al-Masjid Al-Haram) saat melaksanakan shalat.',                                                                                                                     'worship',  'easy'),
('w8',  'Berapakah jumlah zakat fitrah yang harus dikeluarkan per orang?',                           '["1 kg beras","2,5 kg atau 3,5 liter beras","5 kg beras","10 kg beras"]',                                                      1, 'Zakat fitrah setara dengan 2,5 kg atau 3,5 liter beras.',                                                                                                                                                  'Zakat fitrah wajib dikeluarkan di akhir Ramadan sebesar satu sha'' makanan pokok, yang setara dengan sekitar 2,5 kg atau 3,5 liter beras.',                                                                             'worship',  'medium'),
('w9',  'Mengusap telinga saat wudhu hukumnya...',                                                   '["Wajib","Sunnah","Haram","Makruh"]',                                                                                          1, 'Mengusap telinga adalah sunnah wudhu.',                                                                                                                                                                    'Dalam wudhu, terdapat rukun yang wajib dilakukan dan sunnah yang jika dilakukan menambah pahala, seperti mengusap telinga.',                                                                                            'worship',  'medium'),
('w10', 'Shalat sunnah yang mengiringi shalat fardhu disebut shalat...',                             '["Tahajjud","Witir","Rawatib","Istikharah"]',                                                                                   2, 'Shalat Rawatib adalah pendamping shalat fardhu.',                                                                                                                                                         'Shalat sunnah Rawatib adalah shalat yang dilakukan sebelum (Qobliyah) atau sesudah (Ba''diyyah) shalat fardhu.',                                                                                                         'worship',  'medium'),
-- General
('g1',  'Berapa jumlah surah dalam Al-Qur''an?',                                                     '["112","113","114","115"]',                                                                                                    2, 'Al-Qur''an terdiri dari 114 surah, dimulai dari Al-Fatihah hingga An-Nas.',                                                                                                                                'Al-Qur''an diturunkan secara bertahap kepada Nabi Muhammad SAW. Kitab suci ini terbagi menjadi 30 Juz dan terdiri dari 114 Surah.',                                                                                     'general',  'easy'),
('g2',  'Siapa nama malaikat yang bertugas menyampaikan wahyu?',                                     '["Mikail","Jibril","Israfil","Ridwan"]',                                                                                        1, 'Malaikat Jibril (Gabriel) adalah malaikat yang bertugas menyampaikan wahyu dari Allah kepada para nabi.',                                                                                                  'Beriman kepada malaikat adalah rukun iman kedua. Setiap malaikat memiliki tugas khusus, seperti Jibril pembawa wahyu dan Mikail pembagi rezeki.',                                                                       'general',  'easy'),
('g3',  'Di kota mana Nabi Muhammad SAW lahir?',                                                     '["Madinah","Thaif","Makkah","Badar"]',                                                                                         2, 'Nabi Muhammad SAW lahir di kota Makkah pada tahun 571 Masehi (Tahun Gajah).',                                                                                                                              'Nabi Muhammad SAW lahir pada hari Senin, 12 Rabiul Awal tahun Gajah. Beliau dilahirkan di Makkah, sebuah kota suci di Jazirah Arab.',                                                                                  'general',  'easy'),
('g4',  'Apa nama kitab yang diturunkan kepada Nabi Daud AS?',                                       '["Taurat","Zabur","Injil","Al-Qur''an"]',                                                                                       1, 'Nabi Daud AS menerima kitab Zabur.',                                                                                                                                                                       'Allah menurunkan kitab-kitab kepada para rasul: Taurat (Musa), Zabur (Daud), Injil (Isa), dan Al-Qur''an (Muhammad).',                                                                                                  'general',  'medium'),
('g5',  'Siapakah nama ayah Nabi Muhammad SAW?',                                                     '["Abu Thalib","Abdul Muthalib","Abdullah","Hamzah"]',                                                                          2, 'Ayah Nabi Muhammad adalah Abdullah.',                                                                                                                                                                      'Nabi Muhammad SAW adalah putra dari pasangan Abdullah bin Abdul Muthalib dan Aminah binti Wahb.',                                                                                                                       'general',  'easy'),
('g6',  'Siapakah wanita pertama yang memeluk Islam?',                                               '["Aisyah","Fathimah","Khadijah","Sumayyah"]',                                                                                  2, 'Khadijah adalah orang pertama yang masuk Islam.',                                                                                                                                                         'Istri pertama Nabi Muhammad SAW, Khadijah binti Khuwailid, adalah orang pertama yang beriman dan mendukung dakwah beliau.',                                                                                              'general',  'medium'),
('g7',  'Apa nama bulan pertama dalam kalender Hijriah?',                                            '["Ramadan","Muharram","Syawal","Zulhijjah"]',                                                                                  1, 'Muharram adalah bulan pertama tahun Hijriah.',                                                                                                                                                             'Kalender Islam (Hijriah) terdiri dari 12 bulan, dimulai dari Muharram dan diakhiri dengan Zulhijjah.',                                                                                                                  'general',  'easy'),
('g8',  'Peristiwa perjalanan Nabi Muhammad dari Makkah ke Baitul Maqdis lalu ke langit disebut...', '["Hijrah","Isra Mi''raj","Fathu Makkah","Haji Wada"]',                                                                          1, 'Peristiwa itu disebut Isra Mi''raj.',                                                                                                                                                                       'Isra Mi''raj adalah mukjizat besar di mana Nabi Muhammad SAW diperjalankan dalam satu malam dan menerima perintah shalat lima waktu.',                                                                                   'general',  'medium'),
('g9',  'Siapakah sahabat Nabi yang dijuluki ''Al-Faruq''?',                                         '["Abu Bakar Ash-Shiddiq","Umar bin Khattab","Utsman bin Affan","Ali bin Abi Thalib"]',                                          1, 'Umar bin Khattab dijuluki Al-Faruq.',                                                                                                                                                                     'Umar bin Khattab dikenal karena ketegasannya dalam membedakan yang haq (benar) dan yang bathil (salah), sehingga dijuluki Al-Faruq.',                                                                                    'general',  'hard'),
('g10', 'Surah terpanjang dalam Al-Qur''an adalah...',                                               '["Ali Imran","An-Nisa","Al-Maidah","Al-Baqarah"]',                                                                             3, 'Al-Baqarah adalah surah terpanjang.',                                                                                                                                                                     'Surah Al-Baqarah adalah surah kedua dalam Al-Qur''an dan merupakan surah terpanjang dengan jumlah 286 ayat.',                                                                                                           'general',  'medium');

-- ==================== QURAN SURAHS ====================

INSERT INTO quran_surahs (id, name, arabic_name, english_name, number_of_ayahs, revelation_type, audio_url) VALUES
(1,'Al-Faatiha','الفاتحة','The Opening',7,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/1.mp3'),
(2,'Al-Baqara','البقرة','The Cow',286,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/2.mp3'),
(3,'Aal-i-Imraan','آل عمران','The Family of Imraan',200,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/3.mp3'),
(4,'An-Nisaa','النساء','The Women',176,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/4.mp3'),
(5,'Al-Maaida','المائدة','The Table',120,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/5.mp3'),
(6,'Al-An''aam','الأنعام','The Cattle',165,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/6.mp3'),
(7,'Al-A''raaf','الأعراف','The Heights',206,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/7.mp3'),
(8,'Al-Anfaal','الأنفال','The Spoils of War',75,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/8.mp3'),
(9,'At-Tawba','التوبة','The Repentance',129,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/9.mp3'),
(10,'Yunus','يونس','Jonas',109,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/10.mp3'),
(11,'Hud','هود','Hud',123,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/11.mp3'),
(12,'Yusuf','يوسف','Joseph',111,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/12.mp3'),
(13,'Ar-Ra''d','الرعد','The Thunder',43,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/13.mp3'),
(14,'Ibrahim','إبراهيم','Abraham',52,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/14.mp3'),
(15,'Al-Hijr','الحجر','The Rock',99,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/15.mp3'),
(16,'An-Nahl','النحل','The Bee',128,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/16.mp3'),
(17,'Al-Israa','الإسراء','The Night Journey',111,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/17.mp3'),
(18,'Al-Kahf','الكهف','The Cave',110,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/18.mp3'),
(19,'Maryam','مريم','Mary',98,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/19.mp3'),
(20,'Taa-Haa','طه','Taa-Haa',135,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/20.mp3'),
(21,'Al-Anbiyaa','الأنبياء','The Prophets',112,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/21.mp3'),
(22,'Al-Hajj','الحج','The Pilgrimage',78,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/22.mp3'),
(23,'Al-Muminoon','المؤمنون','The Believers',118,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/23.mp3'),
(24,'An-Noor','النور','The Light',64,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/24.mp3'),
(25,'Al-Furqaan','الفرقان','The Criterion',77,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/25.mp3'),
(26,'Ash-Shu''araa','الشعراء','The Poets',227,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/26.mp3'),
(27,'An-Naml','النمل','The Ant',93,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/27.mp3'),
(28,'Al-Qasas','القصص','The Stories',88,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/28.mp3'),
(29,'Al-Ankaboot','العنكبوت','The Spider',69,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/29.mp3'),
(30,'Ar-Room','الروم','The Romans',60,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/30.mp3'),
(31,'Luqman','لقمان','Luqman',34,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/31.mp3'),
(32,'As-Sajda','السجدة','The Prostration',30,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/32.mp3'),
(33,'Al-Ahzaab','الأحزاب','The Clans',73,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/33.mp3'),
(34,'Saba','سبأ','Sheba',54,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/34.mp3'),
(35,'Faatir','فاطر','The Originator',45,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/35.mp3'),
(36,'Yaseen','يس','Yaseen',83,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/36.mp3'),
(37,'As-Saaffaat','الصافات','Those drawn up in Ranks',182,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/37.mp3'),
(38,'Saad','ص','The letter Saad',88,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/38.mp3'),
(39,'Az-Zumar','الزمر','The Groups',75,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/39.mp3'),
(40,'Ghafir','غافر','The Forgiver',85,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/40.mp3'),
(41,'Fussilat','فصلت','Explained in detail',54,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/41.mp3'),
(42,'Ash-Shura','الشورى','Consultation',53,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/42.mp3'),
(43,'Az-Zukhruf','الزخرف','Ornaments of gold',89,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/43.mp3'),
(44,'Ad-Dukhaan','الدخان','The Smoke',59,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/44.mp3'),
(45,'Al-Jaathiya','الجاثية','Crouching',37,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/45.mp3'),
(46,'Al-Ahqaf','الأحقاف','The Dunes',35,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/46.mp3'),
(47,'Muhammad','محمد','Muhammad',38,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/47.mp3'),
(48,'Al-Fath','الفتح','The Victory',29,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/48.mp3'),
(49,'Al-Hujuraat','الحجرات','The Inner Apartments',18,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/49.mp3'),
(50,'Qaaf','ق','The letter Qaaf',45,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/50.mp3'),
(51,'Adh-Dhaariyat','الذاريات','The Winnowing Winds',60,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/51.mp3'),
(52,'At-Tur','الطور','The Mount',49,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/52.mp3'),
(53,'An-Najm','النجم','The Star',62,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/53.mp3'),
(54,'Al-Qamar','القمر','The Moon',55,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/54.mp3'),
(55,'Ar-Rahmaan','الرحمن','The Beneficent',78,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/55.mp3'),
(56,'Al-Waaqia','الواقعة','The Inevitable',96,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/56.mp3'),
(57,'Al-Hadid','الحديد','The Iron',29,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/57.mp3'),
(58,'Al-Mujaadila','المجادلة','The Pleading Woman',22,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/58.mp3'),
(59,'Al-Hashr','الحشر','The Exile',24,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/59.mp3'),
(60,'Al-Mumtahana','الممتحنة','She that is to be examined',13,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/60.mp3'),
(61,'As-Saff','الصف','The Ranks',14,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/61.mp3'),
(62,'Al-Jumu''a','الجمعة','Friday',11,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/62.mp3'),
(63,'Al-Munaafiqoon','المنافقون','The Hypocrites',11,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/63.mp3'),
(64,'At-Taghaabun','التغابن','Mutual Disillusion',18,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/64.mp3'),
(65,'At-Talaaq','الطلاق','Divorce',12,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/65.mp3'),
(66,'At-Tahrim','التحريم','The Prohibition',12,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/66.mp3'),
(67,'Al-Mulk','الملك','The Sovereignty',30,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/67.mp3'),
(68,'Al-Qalam','القلم','The Pen',52,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/68.mp3'),
(69,'Al-Haaqqa','الحاقة','The Reality',52,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/69.mp3'),
(70,'Al-Ma''aarij','المعارج','The Ascending Stairways',44,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/70.mp3'),
(71,'Nooh','نوح','Noah',28,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/71.mp3'),
(72,'Al-Jinn','الجن','The Jinn',28,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/72.mp3'),
(73,'Al-Muzzammil','المزمل','The Enshrouded One',20,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/73.mp3'),
(74,'Al-Muddaththir','المدثر','The Cloaked One',56,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/74.mp3'),
(75,'Al-Qiyaama','القيامة','The Resurrection',40,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/75.mp3'),
(76,'Al-Insaan','الإنسان','Man',31,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/76.mp3'),
(77,'Al-Mursalaat','المرسلات','The Emissaries',50,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/77.mp3'),
(78,'An-Naba','النبأ','The Announcement',40,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/78.mp3'),
(79,'An-Naazi''aat','النازعات','Those who drag forth',46,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/79.mp3'),
(80,'Abasa','عبس','He frowned',42,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/80.mp3'),
(81,'At-Takwir','التكوير','The Overthrowing',29,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/81.mp3'),
(82,'Al-Infitaar','الانفطار','The Cleaving',19,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/82.mp3'),
(83,'Al-Mutaffifin','المطففين','Defrauding',36,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/83.mp3'),
(84,'Al-Inshiqaaq','الانشقاق','The Splitting Open',25,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/84.mp3'),
(85,'Al-Burooj','البروج','The Mansions of the Stars',22,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/85.mp3'),
(86,'At-Taariq','الطارق','The Morning Star',17,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/86.mp3'),
(87,'Al-A''laa','الأعلى','The Most High',19,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/87.mp3'),
(88,'Al-Ghaashiya','الغاشية','The Overwhelming',26,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/88.mp3'),
(89,'Al-Fajr','الفجر','The Dawn',30,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/89.mp3'),
(90,'Al-Balad','البلد','The City',20,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/90.mp3'),
(91,'Ash-Shams','الشمس','The Sun',15,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/91.mp3'),
(92,'Al-Layl','الليل','The Night',21,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/92.mp3'),
(93,'Ad-Duhaa','الضحى','The Morning Hours',11,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/93.mp3'),
(94,'Ash-Sharh','الشرح','The Relief',8,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/94.mp3'),
(95,'At-Tin','التين','The Fig',8,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/95.mp3'),
(96,'Al-Alaq','العلق','The Clot',19,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/96.mp3'),
(97,'Al-Qadr','القدر','The Power, Fate',5,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/97.mp3'),
(98,'Al-Bayyina','البينة','The Evidence',8,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/98.mp3'),
(99,'Az-Zalzala','الزلزلة','The Earthquake',8,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/99.mp3'),
(100,'Al-Aadiyaat','العاديات','The Chargers',11,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/100.mp3'),
(101,'Al-Qaari''a','القارعة','The Calamity',11,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/101.mp3'),
(102,'At-Takaathur','التكاثر','Competition',8,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/102.mp3'),
(103,'Al-Asr','العصر','The Declining Day',3,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/103.mp3'),
(104,'Al-Humaza','الهمزة','The Traducer',9,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/104.mp3'),
(105,'Al-Fil','الفيل','The Elephant',5,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/105.mp3'),
(106,'Quraysh','قريش','Quraysh',4,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/106.mp3'),
(107,'Al-Maa''un','الماعون','Almsgiving',7,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/107.mp3'),
(108,'Al-Kawthar','الكوثر','Abundance',3,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/108.mp3'),
(109,'Al-Kaafiroon','الكافرون','The Disbelievers',6,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/109.mp3'),
(110,'An-Nasr','النصر','Divine Support',3,'Medinan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/110.mp3'),
(111,'Al-Masad','المسد','The Palm Fibre',5,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/111.mp3'),
(112,'Al-Ikhlaas','الإخلاص','Sincerity',4,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/112.mp3'),
(113,'Al-Falaq','الفلق','The Dawn',5,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/113.mp3'),
(114,'An-Naas','الناس','Mankind',6,'Meccan','https://cdn.islamic.network/quran/audio-surah/128/ar.alafasy/114.mp3');
